services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - /home/asebaai/data/mariadb:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - /home/asebaai/data/wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - /home/asebaai/data/wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress

networks:
  inception: